### ISSUE TITLE
Error starting 'WiredPlayers

### ISSUE THREAD

**Issue by DarylDixonLS** [xabier1989/WiredPlayers-RP#44]
-> Error starting 'WiredPlayers'
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Das System kann die angegebene Datei nicht finden.
   at void WiredPlayers.database.Database.OnResourceStart()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at GTANetworkInternals.ScriptingEngine.InvokeVoidMethod(String method, Object[] args)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at GTANetworkInternals.EventHandler.ParseEx(Event _event, ScriptingEngine engine, Object[] arguments)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at GTANetworkInternals.GameServer.StartResource(String resourceName, String parent)

Started! Waiting for connections..

**Comment by xabier1989** [comment]
Follow the steps one by one, you're missing System.Text.Encoding.CodePages from Github, as you can read there.

**Comment by DarylDixonLS** [comment]
Got it! Server starts without error! But nothing happens! 
https://www.bilder-upload.eu/upload/426d8f-1545058386.jpg
