### ISSUE TITLE
Error in SQL Syntax at SaveCharacterInformation

### ISSUE THREAD

**Issue by spiderZ18** [xabier1989/WiredPlayers-RP#9]
[EXCEPTION SaveCharacterInformation]    at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at WiredPlayers.database.Database.SaveCharacterInformation(PlayerModel player) in D:\RageMP\server-files\bridge\resources\WiredPlayers\database\Database.cs:line 539

**Comment by xabier1989** [comment]
If you're using MySQL 8.0 try switching to 5.6, someone fixed his issue with that.

**Comment by spiderZ18** [comment]
Thank you, that fixed the problem!

xabier1989 <notifications@github.com> schrieb am Di., 19. Juni 2018, 15:54:
