### ISSUE TITLE
Error starting 'WiredPlayers'

### ISSUE THREAD

**Issue by EagleCore** [xabier1989/WiredPlayers-RP#93]
I did everything in this tutorial.
`-> Error starting 'WiredPlayers'
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'MySql.Data, Version=8.0.16.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d'. The system cannot find the file specified.

   at List<BusinessModel> WiredPlayers.database.Database.LoadAllBusiness()
   at void WiredPlayers.business.Business.LoadDatabaseBusiness() in /root/ragemp-srv/bridge/resources/WiredPlayers/business/Business.cs:line 21
   at void WiredPlayers.database.Database.OnResourceStart() in /root/ragemp-srv/bridge/resources/WiredPlayers/database/Database.cs:line 46
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at GTANetworkInternals.ScriptingEngine.InvokeVoidMethod(String method, Object[] args)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at GTANetworkInternals.EventHandler.ParseEx(Event _event, ScriptingEngine engine, Object[] arguments)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at GTANetworkInternals.GameServer.StartResource(String resourceName, String parent)

Started! Waiting for connections..
[P] Plugin bridge.so loaded!
Started HTTP server at 22006 port.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at WiredPlayers.globals.Globals.OnMinuteSpent(Object unused) in /root/ragemp-srv/bridge/resources/WiredPlayers/globals/Globals.cs:line 214
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()`

**Comment by xabier1989** [comment]
You updated the MySQL.Data version, you need to copy the .dll into /runtime folder or use 8.0.15 again.

**Comment by EagleCore** [comment]
Okay now I have this error:


-> Error starting 'WiredPlayers'
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format.
 (Exception from HRESULT: 0x8007000B)
   at List<BusinessModel> WiredPlayers.database.Database.LoadAllBusiness()
   at void WiredPlayers.business.Business.LoadDatabaseBusiness() in /root/ragemp-srv/bridge/resources/WiredPlayers/business/Business.cs:line 21
   at void WiredPlayers.database.Database.OnResourceStart() in /root/ragemp-srv/bridge/resources/WiredPlayers/database/Database.cs:line 46
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at GTANetworkInternals.ScriptingEngine.InvokeVoidMethod(String method, Object[] args)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at GTANetworkInternals.EventHandler.ParseEx(Event _event, ScriptingEngine engine, Object[] arguments)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at GTANetworkInternals.GameServer.StartResource(String resourceName, String parent)

Started! Waiting for connections..
[P] Plugin bridge.so loaded!
Started HTTP server at 22006 port.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at WiredPlayers.globals.Globals.OnMinuteSpent(Object unused) in /root/ragemp-srv/bridge/resources/WiredPlayers/globals/Globals.cs:line 214
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
